# docker-compose -f docker-compose.yml up -d
# docker-compose ps
# docker-compose -f docker-compose.yml down
# visit http://localhost:5388/
spingcloud-discovery-eureka-server:
    image: krmao/spingcloud-discovery-eureka-server
    container_name: spingcloud-discovery-eureka-server
    ports:
        - "5388:5388"
spingcloud-app-a:
    image: krmao/spingcloud-app-a
    container_name: spingcloud-app-a
    ports:
        - "5380:5380"
    links:
        - spingcloud-discovery-eureka-server:eureka-server
    environment:
        eureka.client.service-url.defaultZone: http://eureka-server:5388/eureka
spingcloud-app-b:
    image: krmao/spingcloud-app-b
    container_name: spingcloud-app-b
    ports:
        - "5381:5381"
    links:
        - spingcloud-discovery-eureka-server:eureka-server
    environment:
        eureka.client.service-url.defaultZone: http://eureka-server:5388/eureka
spingcloud-routing-zuul:
    image: krmao/spingcloud-routing-zuul
    container_name: spingcloud-routing-zuul
    ports:
        - "5389:5389"
    links:
        - spingcloud-discovery-eureka-server:eureka-server
    environment:
        eureka.client.service-url.defaultZone: http://eureka-server:5388/eureka
