# Chinese comments will call Caused by: org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 2
# error on Windows system, but well on Mac system

# https://stackoverflow.com/a/29194250/4348530
debug: ${server_debug}

server:
    # port: 5382 # http://localhost:5386/apps-app-b-dev.yml
    servlet:
        context-path: /app-b

eureka:
    client:
        service-url:
            # eureka-server address
            defaultZone: http://10.32.33.21:5388/eureka
        register-with-eureka: true
        fetch-registry: true
    instance:
        hostname: \${spring.cloud.client.ip-address}
        prefer-ip-address: true
        # https://www.jianshu.com/p/5ad8317961b7
        # https://stackoverflow.com/a/29194250/4348530
        instance-id: \${spring.cloud.client.ip-address}:\${server.port}\${server.servlet.context-path}@${app_a_version}

# eureka-client-a call eureka-client-b , config in eureka-client-a
# https://www.cnblogs.com/zhainan-blog/p/11634621.html
ribbon:
    ReadTimeout: 5000
    ConnectTimeout: 5000
    eager-load:
        enabled: false
        clients:  http://10.32.33.21:5388/eureka
        MaxTotalConnections: 2000
        MaxConnectionsPerHost: 1000
        maxAutoRetries: 2
        maxAutoRetriesNextServer: 2
        okToRetryOnAllOperations: true
        retryableStatusCodes: 500,404,502
        ###eureka-provider:
        ### ribbon:
        ###   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
    command:
        default:
            circuitBreaker:
                enabled: false
                requestVolumeThreshold: 10
                errorThresholdPercentage: 50
                forceOpen: false
                forceClosed: false
            fallback:
                enabled: true
            execution:
                timeout:
                    # https://www.cnblogs.com/throwable/p/11961016.html
                    enabled: false
            isolation:
                semaphore:
                    maxConcurrentRequests: 4
                strategy: THREAD
                thread:
                    timeoutInMilliseconds: 1000
                    # https://www.cnblogs.com/throwable/p/11961016.html
                    interruptOnTimeout: true
                    interruptOnCancel: true

    # https://blog.csdn.net/weixin_33809981/article/details/88678620
    threadpool:
        default:
            coreSize: 2
            maxQueueSize: 8

feign:
    hystrix:
        enabled: true
    compression:
        request:
            enabled: true
            mime-types: ["text/xml", "application/xml","application/json"]
        response:
            enabled: true
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 5000
                loggerLevel: full

spring:
    main:
        # if call multi time @EnableFeignClients, will cause error bellow, set allow-bean-definition-overriding will avoid error, so try ony call once @EnableFeignClients
        # org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'APP-TEMPLATE-B.FeignClientSpecification'
        # defined in null: Cannot register bean definition [Generic bean: class [org.springframework.cloud.openfeign.FeignClientSpecification];
        allow-bean-definition-overriding: false
    application:
        # name in eureka-server
        name: APP-B
    cloud:
        config:
            allow-override: true
            override-none: true
            override-system-properties: true
            label: master # 配置仓库的分支
            profile: dev # 环境 env
            name: apps-app-b # Name of application used to fetch remote properties.
            discovery:  # 配置服务发现
                enabled: true  # 是否启动服务发现
                serviceId: CONFIG-SERVER # 服务发现(eureka)中，配置中心(config server)的服务名
    resources:
        cache:
            # https://www.twblogs.net/a/5b8c454a2b7177188331c861
            period: 15s
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/,classpath:/static/
    #    thymeleaf:
    #        suffix: .html
    #        prefix: classpath:/templates/
    jackson:
        default-property-inclusion: non_null
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    http:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

# TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
logging:
    level:
        root: WARN
        com.smart: DEBUG
        static: WARN
        org.springframework:
            data: WARN
            security: WARN
