# 运行好后访问 http://localhost:5386/apps-app-a.yml 测试
server:
    port: 5386

spring:
    application:
        # 服务名称 - 服务之间使用名称进行通讯
        name: CONFIG-SERVER
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/krmao/springcloud-config-repo # 配置git仓库地址
                    search-paths: files # 配置仓库路径
                    username: # 访问git仓库的用户名, 如果Git仓库为公开仓库，可以不填写用户名和密码
                    password: # 访问git仓库的用户密码, 如果Git仓库为公开仓库，可以不填写用户名和密码
            label: master # 配置仓库的分支
              # profile: dev # 环境 env
              # name: server1 # Name of application used to fetch remote properties.
              # discovery:  # 配置服务发现
              # enabled: true  # 是否启动服务发现
            # serviceId: CONFIG-SERVER # 服务发现(eureka)中，配置中心(config server)的服务名

eureka:
    client:
        service-url:
            # 配置 eureka 服务器地址
            defaultZone: http://10.32.33.21:5388/eureka
        register-with-eureka: true
        fetch-registry: true
    instance:
        hostname: \${spring.cloud.client.ip-address}
        # 使用ip地址注册到注册中心
        prefer-ip-address: true
        # https://www.jianshu.com/p/5ad8317961b7
        # 注册中心列表中显示的状态参数, 对应 eureka-server 控制面板中的 Status 参数
        # https://stackoverflow.com/a/29194250/4348530
        instance-id: \${spring.cloud.client.ip-address}:\${server.port}\${server.servlet.context-path}@${spingcloud_config_server_version}
