target 'App' do
  
  flutter_application_path = '/Users/krmao/workspace/template/mobile/flutter_module/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
  
end
