source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
platform :ios, '9.0'
install! 'cocoapods', generate_multiple_pod_projects: true

def localPod
  pod 'LibraryBase',:path => '../../Libraries/LibraryBase'
  pod 'LibraryHybird',:path => '../../Libraries/LibraryHybird'
  pod 'LibraryReactNative',:path => '../../Libraries/LibraryReactNative'
  pod 'LibraryFlutter',:path => '../../Libraries/LibraryFlutter'
  pod 'LibraryRepository',:path => '../../Libraries/LibraryRepository'
end

def rnpod
  
  # ==================== REACT NATIVE =============
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../../../../web/react_native/node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge', # Include this for RN >= 0.47
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', # needed for debugging
  # Add any other subspecs you want to use in your project
  'RCTActionSheet',
  'RCTGeolocation',
  'RCTImage',
  'RCTPushNotification',
  'RCTSettings',
  'RCTVibration',
  'RCTLinkingIOS',
  ]
  
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => "../../rn-smarttravel/node_modules/react-native/ReactCommon/yoga"
  
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../../rn-smarttravel/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../../rn-smarttravel/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../../rn-smarttravel/node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  
  # When using RN in combination with Cocoapods, a lot of
  # things are broken. These are the fixes we had to append
  # to our Podfile when upgrading to ReactNative@0.55.3.
  #
  # WARNING: Check those line numbers when you're on a different version!
  
  def change_lines_in_file(file_path, &change)
    print "Fixing #{file_path}...\n"
    
    contents = []
    
    file = File.open(file_path, 'r')
    file.each_line do |line|
      contents << line
    end
    file.close
    
    File.open(file_path, 'w') do |f|
      f.puts(change.call(contents))
    end
  end
  
  post_install do |installer|
    
    # https://github.com/facebook/yoga/issues/711#issuecomment-374605785
    change_lines_in_file('../../rn-smarttravel/node_modules/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h') do |lines|
      unless lines[27].include?("#ifdef __cplusplus")
        lines.insert(27, "#ifdef __cplusplus")
        lines.insert(34, "#endif")
      end
      lines
    end
    
    # https://github.com/facebook/react-native/issues/13198
    change_lines_in_file('../../rn-smarttravel/node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h') do |lines|
      lines.map {|line| line.include?("#import <RCTAnimation/RCTValueAnimatedNode.h>") ? '#import "RCTValueAnimatedNode.h"' : line}
    end
    
    # https://github.com/facebook/react-native/issues/16039
    change_lines_in_file('../../rn-smarttravel/node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m') do |lines|
      lines.map {|line| line.include?("#import <fishhook/fishhook.h>") ? '#import "fishhook.h"' : line}
    end
    
    # 消除警告 The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'AFNetworking') 等
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
      end
    end
  end
end


flutter_application_path = '/Users/krmao/workspace/template/mobile/flutter/'
#load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'App' do
  inherit! :search_paths
  
  localPod
#  rnpod

#  install_flutter_engine_pod
#  install_flutter_plugin_pods flutter_application_path
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
  
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ENABLE_BITCODE'] = 'NO'
#    end
#  end
#end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
#install! 'cocoapods', :disable_input_output_paths => true
