source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!


target 'fruit-shop-ios' do
  # pod '**', :git => 'http://**.git'
  pod 'IQKeyboardManagerSwift' #,'4.0.10'
  pod 'SnapKit', '~> 3.2.0'
  # pod 'AFNetworking', '~> 3.0'
  pod 'Alamofire', '~> 4.4'

end
