source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"
use_frameworks!

inhibit_all_warnings!

# /usr/bin/ruby /Applications/AppCode.app/Contents/bin/pod install --no-ansi

target 'template' do
  # pod '**', :git => 'http://**.git'

  pod 'TransitionableTab', '~> 0.1.2'

  # ==================== 布局库 ====================
  pod 'SnapKit', '~> 4.0.0'

  # ==================== 网络库 ====================
  # pod 'AFNetworking', '~> 3.0'
  pod 'Alamofire', '~> 4.6.0'
  # pod 'Moya', '~> 10.0'
  pod 'Moya/RxSwift', '~> 10.0'

  # ==================== 工具库 ====================
  pod 'SwiftyBeaver' # 日志
  # pod 'IQKeyboardManagerSwift' #,'4.0.10'
  pod 'Zip', '~> 1.1.0'
  pod 'RxCocoa', '~> 4.1.1'
  pod 'MBProgressHUD', '~> 1.1.0'


  # ==================== REACT NATIVE =============
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../react_native/node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge', # Include this for RN >= 0.47
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # needed for debugging
      # Add any other subspecs you want to use in your project
      'RCTActionSheet',
      'RCTGeolocation',
      'RCTImage',
      'RCTPushNotification',
      'RCTSettings',
      'RCTVibration',
      'RCTLinkingIOS',
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => "../react_native/node_modules/react-native/ReactCommon/yoga"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../react_native/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../react_native/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../react_native/node_modules/react-native/third-party-podspecs/Folly.podspec'


  # When using RN in combination with Cocoapods, a lot of
  # things are broken. These are the fixes we had to append
  # to our Podfile when upgrading to ReactNative@0.55.3.
  #
  # WARNING: Check those line numbers when you're on a different version!

  def change_lines_in_file(file_path, &change)
    print "Fixing #{file_path}...\n"

    contents = []

    file = File.open(file_path, 'r')
    file.each_line do |line|
      contents << line
    end
    file.close

    File.open(file_path, 'w') do |f|
      f.puts(change.call(contents))
    end
  end

  post_install do |installer|
    # https://github.com/facebook/yoga/issues/711#issuecomment-381098373
    change_lines_in_file('./Pods/Target Support Files/yoga/yoga-umbrella.h') do |lines|
      lines.reject do |line|
        [
            '#import "Utils.h"',
            '#import "YGLayout.h"',
            '#import "YGNode.h"',
            '#import "YGNodePrint.h"',
            '#import "YGStyle.h"',
            '#import "Yoga-internal.h"',
        ].include?(line.strip)
      end
    end

    # https://github.com/facebook/yoga/issues/711#issuecomment-374605785
    change_lines_in_file('../react_native/node_modules/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h') do |lines|
      unless lines[27].include?("#ifdef __cplusplus")
        lines.insert(27, "#ifdef __cplusplus")
        lines.insert(34, "#endif")
      end
      lines
    end

    # https://github.com/facebook/react-native/issues/13198
    change_lines_in_file('../react_native/node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h') do |lines|
      lines.map {|line| line.include?("#import <RCTAnimation/RCTValueAnimatedNode.h>") ? '#import "RCTValueAnimatedNode.h"' : line}
    end

    # https://github.com/facebook/react-native/issues/16039
    change_lines_in_file('../react_native/node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m') do |lines|
      lines.map {|line| line.include?("#import <fishhook/fishhook.h>") ? '#import "fishhook.h"' : line}
    end
  end

end
