source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"
use_frameworks!

inhibit_all_warnings!

# /usr/bin/ruby /Applications/AppCode.app/Contents/bin/pod install --no-ansi

target 'template' do
  # pod '**', :git => 'http://**.git'

  # ==================== 布局库 ====================
  pod 'SnapKit', '~> 4.0.0'

  # ==================== 网络库 ====================
  # pod 'AFNetworking', '~> 3.0'
  pod 'Alamofire', '~> 4.6.0'
  # pod 'Moya', '~> 10.0'
  pod 'Moya/RxSwift', '~> 10.0'

  # ==================== 工具库 ====================
  pod 'SwiftyBeaver' # 日志
  # pod 'IQKeyboardManagerSwift' #,'4.0.10'
  pod 'Zip', '~> 1.1.0'
  pod 'RxCocoa', '~> 4.1.1'
  pod 'MBProgressHUD', '~> 1.1.0'


  # ==================== REACT NATIVE =============
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../react_native/node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge', # Include this for RN >= 0.47
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # needed for debugging
  # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => "../react_native/node_modules/react-native/ReactCommon/yoga"
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../react_native/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../react_native/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../react_native/node_modules/react-native/third-party-podspecs/Folly.podspec'

end
