server:
    port: 5388

spring:
    application:
        name: ERUREKA-SERVER

#======================================================================
# 配置 actuator start https://stackoverflow.com/a/24868636/4348530
#======================================================================
info:
    application-name: EUREKA-SERVER
management:
    endpoints:
        web:
            exposure:
                include: '*'
            base-path: /actuator
    endpoint:
        health:
            show-details: always
#======================================================================
# 配置 actuator end
#======================================================================
#======================================================================
# 配置 eureka start
#======================================================================
eureka:
    client:
        healthcheck:
            enabled: true                          # 开启健康检查（依赖spring-boot-starter-actuator）
        service-url:
            defaultZone: http://10.32.33.15:5388/eureka
        register-with-eureka: true                 # 是否将自己注册到 Eureka Server
        fetch-registry: false                      # 是否从 Eureka Server 获取注册的服务信息
        registry-fetch-interval-seconds: 30        # eureka client 间隔多久去拉取服务注册信息, 默认为30秒
    instance:
        prefer-ip-address: true
        hostname: ${spring.cloud.client.ip-address}
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
        lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
        lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）

        # config with actuator start
        # 如果项目配置有 server.servlet.context-path 属性, 想要被 spring boot admin 监控, 就要配置以下属性
        health-check-url-path: /actuator/health
        status-page-url-path: /actuator/info
        metadata-map:
            management:
                context-path: /actuator
        # config with actuator end
#======================================================================
# 配置 eureka end
#======================================================================
