server:
    port: 9000

spring:
    application:
        name: AUTH-SERVER             # 服务名称 - 服务之间使用名称进行通讯

#======================================================================
# 配置 actuator start https://stackoverflow.com/a/24868636/4348530
#======================================================================
info:
    application-name: AUTH-SERVER
management:
    endpoints:
        web:
            exposure:
                include: '*'
            base-path: /actuator
    endpoint:
        health:
            show-details: always
#======================================================================
# 配置 actuator end
#======================================================================
#======================================================================
# 配置 eureka start
#======================================================================
eureka:
    client:
        service-url:
            defaultZone: http://10.32.33.15:5388/eureka
        register-with-eureka: true
        fetch-registry: true
        registry-fetch-interval-seconds: 15
        initialInstanceInfoReplicationIntervalSeconds: 40
        region: region-auth-server              # 默认为 "us-east-1"
        availability-zones:
            codes-dancing-region: zone-auth-server

    instance:
        initial-status: UP
        prefer-ip-address: true
        hostname: \${spring.cloud.client.ip-address}
        instance-id: \${spring.cloud.client.ip-address}:\${server.port}
        lease-renewal-interval-in-seconds: 15

        # config with actuator start
        # 如果项目配置有 server.servlet.context-path 属性, 想要被 spring boot admin 监控, 就要配置以下属性
        health-check-url-path: /actuator/health
        status-page-url-path: /actuator/info
        metadata-map:
            management:
                context-path: /actuator
        # config with actuator end
#======================================================================
# 配置 eureka end
#======================================================================

logging:
    level:
        root: INFO
        org.springframework.web: INFO
        org.springframework.security: INFO
        org.springframework.security.oauth2: INFO
