server:
    port: 5389
    servlet:
        context-path: /api-gateway

spring:
    application:
        # 服务名称 - 服务之间使用名称进行通讯
        name: API-GATEWAY
zuul:
    routes:
        # 设置服务a 路径名称 随便起
        service-a:
            path: /service-a/**
            # 这里写a服务的注册名字
            serviceId: APP-A
        # 设置服务b 路径名称 随便起
        service-b:
            path: /service-b/**
            # 这里写b服务的注册名字
            serviceId: APP-B


#======================================================================
# 配置 actuator start https://stackoverflow.com/a/24868636/4348530
#======================================================================
info:
    application-name: API-GATEWAY
management:
    endpoints:
        web:
            exposure:
                include: '*'
            base-path: /actuator
    endpoint:
        health:
            show-details: always
#======================================================================
# 配置 actuator end
#======================================================================
#======================================================================
# 配置 eureka start
#======================================================================
eureka:
    client:
        service-url:
            defaultZone: http://10.32.33.19:5388/eureka
        register-with-eureka: true
        fetch-registry: true
        registry-fetch-interval-seconds: 15
        initialInstanceInfoReplicationIntervalSeconds: 40
        region: region-api-gateway              # 默认为 "us-east-1"
        availability-zones:
            codes-dancing-region: zone-api-gateway

    instance:
        initial-status: UP
        prefer-ip-address: true
        hostname: \${spring.cloud.client.ip-address}
        instance-id: \${spring.cloud.client.ip-address}:\${server.port}\${server.servlet.context-path}
        lease-renewal-interval-in-seconds: 15

        # config with actuator start
        # 如果项目配置有 server.servlet.context-path 属性, 想要被 spring boot admin 监控, 就要配置以下属性
        health-check-url-path: \${server.servlet.context-path}/actuator/health
        status-page-url-path: \${server.servlet.context-path}/actuator/info
        metadata-map:
            management:
                context-path: \${server.servlet.context-path}/actuator
        # config with actuator end
#======================================================================
# 配置 eureka end
#======================================================================
