server:
    port: 5389
    servlet:
        context-path: /api-gateway

eureka:
    client:
        service-url:
            # 配置 eureka 服务器地址
            defaultZone: http://10.32.33.4:5388/eureka
    instance:
        hostname: \${spring.cloud.client.ip-address}
        # 使用ip地址注册到注册中心
        prefer-ip-address: true
        # https://www.jianshu.com/p/5ad8317961b7
        # 注册中心列表中显示的状态参数, 对应 eureka-server 控制面板中的 Status 参数
        # https://stackoverflow.com/a/29194250/4348530
        instance-id: \${spring.cloud.client.ip-address}:\${server.port}\${server.servlet.context-path}@${app_a_version}

spring:
    application:
        # 服务名称 - 服务之间使用名称进行通讯
        name: API-GATEWAY
zuul:
    routes:
        # 设置服务a 路径名称 随便起
        service-a:
            path: /service-a/**
            # 这里写a服务的注册名字
            # http://10.32.33.4:5390/service-a/app-template-a/test/callB?token=123
            serviceId: APP-A
        # 设置服务b 路径名称 随便起
        service-b:
            path: /service-b/**
            # 这里写b服务的注册名字
            serviceId: APP-B
