source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

platform :ios, '9.0'
install! 'cocoapods', generate_multiple_pod_projects: true

def rnpod
  pod 'LibraryReactNative', :path => '../Libraries/LibraryReactNative'

  # ==================== REACT NATIVE =============
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../../../react_native/node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge', # Include this for RN >= 0.47
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # needed for debugging
      # Add any other subspecs you want to use in your project
      'RCTActionSheet',
      'RCTGeolocation',
      'RCTImage',
      'RCTPushNotification',
      'RCTSettings',
      'RCTVibration',
      'RCTLinkingIOS',
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => "../../rn-smarttravel/node_modules/react-native/ReactCommon/yoga"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../../rn-smarttravel/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../../rn-smarttravel/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../../rn-smarttravel/node_modules/react-native/third-party-podspecs/Folly.podspec'

  # When using RN in combination with Cocoapods, a lot of
  # things are broken. These are the fixes we had to append
  # to our Podfile when upgrading to ReactNative@0.55.3.
  #
  # WARNING: Check those line numbers when you're on a different version!

  def change_lines_in_file(file_path, &change)
    print "Fixing #{file_path}...\n"
    contents = []
    file = File.open(file_path, 'r')
    file.each_line do |line|
      contents << line
    end
    file.close

    File.open(file_path, 'w') do |f|
      f.puts(change.call(contents))
    end
  end

  post_install do |installer|

    # https://github.com/facebook/yoga/issues/711#issuecomment-374605785
    change_lines_in_file('../../rn-smarttravel/node_modules/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h') do |lines|
      unless lines[27].include?("#ifdef __cplusplus")
        lines.insert(27, "#ifdef __cplusplus")
        lines.insert(34, "#endif")
      end
      lines
    end

    # https://github.com/facebook/react-native/issues/13198
    change_lines_in_file('../../rn-smarttravel/node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h') do |lines|
      lines.map { |line| line.include?("#import <RCTAnimation/RCTValueAnimatedNode.h>") ? '#import "RCTValueAnimatedNode.h"' : line }
    end

    # https://github.com/facebook/react-native/issues/16039
    change_lines_in_file('../../rn-smarttravel/node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m') do |lines|
      lines.map { |line| line.include?("#import <fishhook/fishhook.h>") ? '#import "fishhook.h"' : line }
    end

    # 消除警告 The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'AFNetworking') 等
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
      end
    end
  end
end

# https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk
def flutterPodWithSourceCode
  flutter_application_path = '../../flutter_module/'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)
end

# https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-c---embed-application-and-plugin-frameworks-in-xcode-and-flutter-framework-with-cocoapods
# https://github.com/CocoaPods/CocoaPods/issues/2860#issuecomment-273208880
# https://github.com/flutter/flutter/issues/50204
#$ xcrun xcodebuild -alltargets -sdk iphoneos -configuration "Debug" ONLY_ACTIVE_ARCH=NO
#$ xcrun xcodebuild -alltargets -sdk iphoneos -configuration "Profile" ONLY_ACTIVE_ARCH=NO
#$ xcrun xcodebuild -alltargets -sdk iphoneos -configuration "Release" ONLY_ACTIVE_ARCH=NO
#flutter build ios-framework --cocoapods --pub --debug --no-profile --output=/Users/krmao/workspace/template/mobile/flutter_module/build-repo/ios -v
def flutterPodWithCocoaPodSpec
  pod 'LibraryFlutter', :path => '../Libraries/LibraryFlutter'

  ENV['POD_RELEASE'] = 'false'
  puts "ENV['POD_RELEASE']=" + ENV['POD_RELEASE']

  if ENV['POD_RELEASE'] == 'true'
    pod 'Flutter', :podspec => '../../flutter_module/build-repo/ios/Release/Flutter.podspec', :configurations => ['Release']
  else
    pod 'Flutter', :podspec => '../../flutter_module/build-repo/ios/Debug/Flutter.podspec', :configurations => ['Debug']
  end

  pod 'FlutterPluginRegistrant', :podspec => '../../flutter_module/.ios/Flutter/FlutterPluginRegistrant/FlutterPluginRegistrant.podspec'

end

target 'Template' do
  inherit! :search_paths

  # 约束布局
  # 会出现大量警告 https://github.com/SnapKit/Masonry/issues/566
  # pod 'Masonry'
  # https://github.com/SnapKit/Masonry/issues/566#issuecomment-544136418 消除警告的第三方分支, pod 引用不要加 tag
  pod 'Masonry' , :git => 'https://github.com/warpling/Masonry.git' # , :tag => 'v1.1.0'

  # 网络请求库
  pod 'AFNetworking', '~> 4.0'
  
  # 异步加载图片
  pod 'SDWebImage', '~> 5.0'
  
  # 解析数据 json to model
  pod 'YYModel'
  
  # 下拉刷新 pull to refresh
  pod 'MJRefresh'
  
  # 键盘遮挡问题 https://github.com/hackiftekhar/IQKeyboardManager
  # pod 'IQKeyboardManager'
  
  # 加载框
  pod 'MBProgressHUD', '~> 1.2.0'
  
  # 轮播图 https://github.com/gsdios/SDCycleScrollView
  pod 'SDCycleScrollView','>= 1.80'
  
  # 事件订阅 https://github.com/LeoMobileDeveloper/QTEventBus
  pod 'QTEventBus'
  
  # 数据为空时显示的页面 https://github.com/dzenbot/DZNEmptyDataSet
  pod 'DZNEmptyDataSet'
  
  # 动画 https://github.com/airbnb/lottie-ios
  pod 'lottie-ios','2.5.3'
  
  # 集成 react native
  # rnpod
  
  # 集成 flutter
  flutterPodWithSourceCode
  # flutterPodWithCocoaPodSpec
  
end
