# source 'https://github.com/CocoaPods/Specs.git'                   # https://github.com/CocoaPods/CocoaPods/issues/2861
source 'https://cdn.cocoapods.org/'                                 # 指明依赖库的来源地址
inhibit_all_warnings!                                               # 忽略引入库的所有警告（强迫症者的福音啊）
platform :ios, '9.0'                                                # 平台是ios，版本是9.0
install! 'cocoapods', generate_multiple_pod_projects: true, :warn_for_unused_master_specs_repo => false # 安装引入Podfile里面的依赖库

target 'Template' do
  inherit! :search_paths
  # pod 'Masonry'                                                   # 会出现大量警告 https://github.com/SnapKit/Masonry/issues/566
  pod 'Masonry', :git => 'https://github.com/warpling/Masonry.git'  # , :tag => 'v1.1.0'  # https://github.com/SnapKit/Masonry/issues/566#issuecomment-544136418
  pod 'AFNetworking', '~> 4.0'                                      # 网络请求库
  pod 'SDWebImage', '~> 5.0'                                        # 异步加载图片
  pod 'YYModel'                                                     # 解析数据 json to model
  pod 'MJRefresh'                                                   # 下拉刷新 pull to refresh
  pod 'IQKeyboardManager'                                           # 键盘遮挡问题 https://github.com/hackiftekhar/IQKeyboardManager
  pod 'MBProgressHUD', '~> 1.2.0'                                   # 加载框
  pod 'SDCycleScrollView', '>= 1.80'                                # 轮播图 https://github.com/gsdios/SDCycleScrollView
  pod 'DZNEmptyDataSet'                                             # 数据为空时显示的页面 https://github.com/dzenbot/DZNEmptyDataSet
  pod 'lottie-ios', '2.5.3'                                         # 动画 https://github.com/airbnb/lottie-ios
  pod 'SSZipArchive'                                                # 压缩/解压缩工具 https://github.com/ZipArchive/ZipArchive
  
  eval(File.read('PodReactNative.rb'))                              # eval方式支持解析source源, load加载的方式则不支持 # load 'PodReactNative.rb'            
  rnpodremote                                                       # rnpodlocal "../../react_native/node_modules"

  load 'PodFlutter.rb'
  # flutterPodWithSourceCode
  # flutterPodWithCocoaPodSpec
  
  load 'PodTools.rb'
  removeLibDeploymentTarget
end

# Podfile 规则参考
# https://www.jianshu.com/p/b8b889610b7e
# http://saitjr.com/ios/the-best-practice-of-parsing-podfile.html?utm_source=tuicool&utm_medium=referral
